### ISSUE TITLE
Crash main.(*Player).ReadByteArray

### ISSUE THREAD

**Issue by FixTheAdmin** [TyphoonMC/TyphoonCore#10]
goroutine 1402 [running]:
main.(*Player).ReadByteArray(0xc42016a460, 0xffffffffffffffc7, 0xc4203d5b30, 0x42, 0x43, 0x0, 0x0)
        /home/earthmc/servers/hublite/1.0.4/TyphoonLimbo-1.0.4/utils.go:245 +0x40
main.(*PacketPlayPluginMessage).Read(0xc4204a2090, 0xc42016a460, 0xa, 0x5a4f60, 0xc4204a2090)
        /home/earthmc/servers/hublite/1.0.4/TyphoonLimbo-1.0.4/packet_handle.go:414 +0x127
main.(*Player).HandlePacket(0xc42016a460, 0x9, 0xa, 0xc4200d1378, 0x1, 0x0, 0x0)
        /home/earthmc/servers/hublite/1.0.4/TyphoonLimbo-1.0.4/packet_registry.go:62 +0x335
main.(*Player).ReadPacketWithoutCompression(0xc42016a460, 0x0, 0x0, 0x0, 0x0)
        /home/earthmc/servers/hublite/1.0.4/TyphoonLimbo-1.0.4/connection.go:195 +0xb8
main.(*Player).ReadPacket(0xc42016a460, 0x0, 0x0, 0x0, 0x0)
        /home/earthmc/servers/hublite/1.0.4/TyphoonLimbo-1.0.4/connection.go:175 +0x72
main.HandleConnection(0x5a56e0, 0xc4202ca048, 0x56e)
        /home/earthmc/servers/hublite/1.0.4/TyphoonLimbo-1.0.4/limbo.go:84 +0x36e
created by main.main
        /home/earthmc/servers/hublite/1.0.4/TyphoonLimbo-1.0.4/limbo.go:32 +0x1fa

This happens on both 1.13.2 and 1.14 builds.

**Comment by FixTheAdmin** [comment]
This is the most serious issue for me right now. It usually crashes after 15 minutes of being online on the 1.14 version. Same thing happens on 1.13.2 but it usually takes longer until it crashes, not sure it's relevant to the issue. I can also add that around 300 players pass the server while it's up.

**Comment by skyforce77** [comment]
Sometimes, the PacketPluginMessage seems to create issues. It can depend on your usage.

Which proxy are you using ?

**Comment by FixTheAdmin** [comment]
Thanks for the reply. I use waterfall.
