### ISSUE TITLE
panic: runtime error: makeslice: len out of range

### ISSUE THREAD

**Issue by mikroskeem** [TyphoonMC/TyphoonCore#6]
```
panic: runtime error: makeslice: len out of range
goroutine 7 [running]:
main.(*Player).ReadByteArray(0xc0000a82a0, 0xfffffffffffffff5, 0xc000112050, 0xb, 0xc, 0x0, 0x0)
     /home/mark/projects/TyphoonLimbo/utils.go:245 +0x40
main.(*PacketPlayPluginMessage).Read(0xc0000ea450, 0xc0000a82a0, 0x1, 0x5afa80, 0xc0000ea450)
     /home/mark/projects/TyphoonLimbo/packet_handle.go:414 +0x123
main.(*Player).HandlePacket(0xc0000a82a0, 0x9, 0x1, 0xc0000b2328, 0xc0000ea301, 0x0, 0x0)
     /home/mark/projects/TyphoonLimbo/packet_registry.go:62 +0x344
main.(*Player).ReadPacketWithoutCompression(0xc0000a82a0, 0x5afa80, 0xc0000ea390, 0x0, 0x0)
     /home/mark/projects/TyphoonLimbo/connection.go:195 +0xb5
main.(*Player).ReadPacket(0xc0000a82a0, 0x5afa80, 0xc0000ea390, 0x0, 0x0)
     /home/mark/projects/TyphoonLimbo/connection.go:175 +0x75
main.HandleConnection(0x5b0200, 0xc00000e0c8, 0x2)
     /home/mark/projects/TyphoonLimbo/limbo.go:84 +0x336
created by main.main
     /home/mark/projects/TyphoonLimbo/limbo.go:32 +0x1fd
```

Player who managed to cause this crash (accidentally) was using 1.8.8 and TyphoonLimbo is running behind Waterfall, if that helps.

**Comment by skyforce77** [comment]
You are right, they aren't mandatory. But this fusion between TyphoonLimbo and TyphoonCore was pending, I can't maintain the two projects independently. It was already "merged", because each commit was duplicated. I was just waiting for golang to update the module system to handle versions
